#!/usr/bin/expect
#### Script to continue SSH session without fingerprint, used with copy.yaml playbook to set up SSH correctly

set timeout -1
set HOME [lindex $argv 0]
#set HOME /home/bent/
spawn ansible-playbook $HOME/devops2/playbooks/copy.yaml

expect "*continue connecting*" { send "yes\r" }

 
