---
##### This play copies the Jenkins Ansible SSH key to EC2-Instance. (We differ between Ansible node, and Ansible Jenkins node using SSH.
  - hosts: ec2
    tasks:
    - name: Copy Jenkins SSH key to EC2-Instance
      ansible.builtin.copy:
        src: /var/lib/jenkins/.ssh/jenkins-key.pub
        dest: /home/ec2-user/
        owner: ec2-user
        group: ec2-user
        mode: 0700

    - name: Import the key using script
      ansible.builtin.script: ssh-import.sh






