## This is the configuration for JCasC , setting the Jenkins Configuration correctly. 
### I've only specified the custom options, the rest will be defaults. 
unclassified:
  location:
    adminAddress: "address not configured yet <nobody@nowhere>"
    url: "http://localhost:8080/"
tool:
  ansibleInstallation:
    installations:
    - home: "/usr/bin/"
      name: "ansible"
  git:
    installations:
    - home: "/usr/bin/git"
      name: "git"
  jdk:
    installations:
    - home: "/usr/lib/jvm/java-11-openjdk-amd64"
      name: "java 8"
  maven:
    installations:
    - home: "/usr/share/maven"
      name: "maven3"
      properties:
      - installSource:
          installers:
          - maven:
              id: "3.6.0"          
jobs:
    - script: >
        pipelineJob("Seed and import all piplines") {
        definition {
            cpsScm {
                scm {
                    git{
                      remote {
                        url("https://github.com/linuxjefeprive/jenkins-seed.git")
                      }
                      branch("*/main")
                    }
                }
            }
          }
        }             
